blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/atemi72/ToDoList/issues/new?template=custom.md&projects=atemi72%2FToDoList%2F1&labels=ToDoList
